timeout: 3600s
steps:
- name: 'us-docker.pkg.dev/gke-windows-tools/docker-repo/gke-windows-builder:latest'
  args:
  - --versions
  - 'ltsc2019'
  - --container-image-name
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/images/contosouniversity-windows:v1'